### ISSUE TITLE
Exception when generating previews

### ISSUE THREAD

**Issue by derritter88** [CollaboraOnline/richdocumentscode#310]
Hello everyone,

running CODE within my Kubernets clusters via Helm chart - values.yml:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora
  namespace: collabora
spec:
  interval: 60m0s
  upgrade:
    force: true
  chart:
    spec:
      chart: collabora-online
      sourceRef:
        kind: HelmRepository
        name: collabora
        namespace: collabora
      interval: 60m0s
  values:
    ingress:
      enabled: false
      className: "haproxy"
      annotations:
        haproxy.org/timeout-tunnel: "3600s"
        haproxy.org/backend-config-snippet: |
          balance url_param WOPISrc check_post
          hash-type consistent
      hosts:
        - host: collabora.hks-projekt.at
          paths:
          - path: /
            pathType: ImplementationSpecific

    image:
      repository: docker.io/collabora/code
      tag: 24.04.13.2.1@sha256:01dc4ab83977edf0f2eb35c07973ac267ebccf4917d3311efa9b9e336709f608
      pullPolicy: IfNotPresent

    autoscaling:
      enabled: false

    collabora:
      aliasgroups:
        - server_name: "https://domain.tld:443"
      extra_params: --o:ssl.enable=false --o:ssl.termination=true --o:net.post_allow.host=10.0.20.100
   
      resources:
        limits:
          cpu: "8000m"
          memory: "8000Mi"
        requests:
          cpu: "4000m"
          memory: "6000Mi"
```

If I trigger to pregenerate image of an Office document I get several exceptions within Nextcloud as well as Pod logs:

Nextcloud:
```
[richdocuments] Fehler: Failed to convert preview: cURL error 28: Operation timed out after 5002 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://collabora.domain.tld/cool/convert-to/png
	von ? von ? um 02.04.2025, 08:12:38
```

The pod logs look like this kind of an endless manner:
```log
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
frk-00024-00024 2025-04-02 06:08:50.866149 +0000 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
kit-00119-00119 2025-04-02 06:08:51.045759 +0000 [ kit_spare_009 ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-57d3498b/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
kit-00119-00119 2025-04-02 06:08:51.045850 +0000 [ kit_spare_009 ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-57d3498b/tmp/sharedpresets/template'| kit/Kit.cpp:594
wsd-00001-00093 2025-04-02 06:08:52.250262 +0000 [ docbroker_004 ] ERR  #35: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1622
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
frk-00024-00024 2025-04-02 06:08:55.977173 +0000 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
kit-00094-00094 2025-04-02 06:08:56.024474 +0000 [ kitbroker_006 ] ERR  Failed to load: file:///tmp/user/docs/RjgYz4dC5HOuf2WU/URD%20-%20Benutzer%20Anforderungsdokument_v0.3.docx, error: loadComponentFromURL returned an empty reference| kit/Kit.cpp:1987
kit-00094-00094 2025-04-02 06:08:56.024513 +0000 [ kitbroker_006 ] ERR  ToMaster-26f: error: cmd=load kind=faileddocloading| common/Session.hpp:181
Failed to load the document. Setting TerminationFlag
kit-00094-00094 2025-04-02 06:08:56.024605 +0000 [ kitbroker_006 ] FTL  Failed to load the document. Setting TerminationFlag| kit/Kit.cpp:2014
kit-00094-00094 2025-04-02 06:08:56.024614 +0000 [ kitbroker_006 ] ERR  ToMaster-26f: Failed to get LoKitDocument instance for [file:///tmp/user/docs/RjgYz4dC5HOuf2WU/URD%20-%20Benutzer%20Anforderungsdokument_v0.3.docx]| kit/ChildSession.cpp:959
wsd-00001-00153 2025-04-02 06:08:56.024827 +0000 [ docbroker_006 ] ERR  ToClient-26f: Document load failed: faileddocloading| wsd/ClientSession.cpp:2096
wsd-00001-00153 2025-04-02 06:08:56.024934 +0000 [ docbroker_006 ] ERR  Unexpected message: [o279 close: ].| wsd/DocumentBroker.cpp:4343
wsd-00001-00153 2025-04-02 06:08:56.025026 +0000 [ docbroker_006 ] WRN  #38: DocBroker [%2Fopt%2Fcool%2Fchild-roots%2F1-57d3498b%2Ftmp%2Fincoming%2Fcool-ZFNOhPIMmxdpq0I1%2FURD%20-%20Benutzer%20Anforderungsdokument_v0.3.docx] got disconnected from its Kit (94) unexpectedly. Closing| wsd/COOLWSD.cpp:2910
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
kit-00154-00154 2025-04-02 06:08:56.186290 +0000 [ kit_spare_00a ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-57d3498b/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
kit-00154-00154 2025-04-02 06:08:56.186383 +0000 [ kit_spare_00a ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-57d3498b/tmp/sharedpresets/template'| kit/Kit.cpp:594
frk-00024-00024 2025-04-02 06:08:58.088155 +0000 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/passwd] is out-of-date. Will have to clone dynamic elements of systemplate to the jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:587
kit-00119-00119 2025-04-02 06:08:58.133685 +0000 [ kitbroker_007 ] ERR  Failed to load: file:///tmp/user/docs/tXX4Qs7PnL7OeNGH/URD%20-%20Benutzer%20Anforderungsdokument_v1.1.docx, error: loadComponentFromURL returned an empty reference| kit/Kit.cpp:1987
kit-00119-00119 2025-04-02 06:08:58.133723 +0000 [ kitbroker_007 ] ERR  ToMaster-271: error: cmd=load kind=faileddocloading| common/Session.hpp:181
Failed to load the document. Setting TerminationFlag
kit-00119-00119 2025-04-02 06:08:58.133766 +0000 [ kitbroker_007 ] FTL  Failed to load the document. Setting TerminationFlag| kit/Kit.cpp:2014
kit-00119-00119 2025-04-02 06:08:58.133773 +0000 [ kitbroker_007 ] ERR  ToMaster-271: Failed to get LoKitDocument instance for [file:///tmp/user/docs/tXX4Qs7PnL7OeNGH/URD%20-%20Benutzer%20Anforderungsdokument_v1.1.docx]| kit/ChildSession.cpp:959
wsd-00001-00164 2025-04-02 06:08:58.133864 +0000 [ docbroker_007 ] ERR  ToClient-271: Document load failed: faileddocloading| wsd/ClientSession.cpp:2096
wsd-00001-00164 2025-04-02 06:08:58.133909 +0000 [ docbroker_007 ] ERR  Unexpected message: [o282 close: ].| wsd/DocumentBroker.cpp:4343
wsd-00001-00164 2025-04-02 06:08:58.133929 +0000 [ docbroker_007 ] WRN  #33: DocBroker [%2Fopt%2Fcool%2Fchild-roots%2F1-57d3498b%2Ftmp%2Fincoming%2Fcool-erZ8jGsWvAJd2LVo%2FURD%20-%20Benutzer%20Anforderungsdokument_v1.1.docx] got disconnected from its Kit (119) unexpectedly. Closing| wsd/COOLWSD.cpp:2910
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
kit-00165-00165 2025-04-02 06:08:58.289710 +0000 [ kit_spare_00b ] ERR  Failed to get the realpath of [/opt/cool/child-roots/1-57d3498b/tmp/sharedpresets/template] (ENOENT: No such file or directory)| common/FileUtil.cpp:284
kit-00165-00165 2025-04-02 06:08:58.289801 +0000 [ kit_spare_00b ] ERR  linkOrCopy: nftw() failed for '/opt/cool/child-roots/1-57d3498b/tmp/sharedpresets/template'| kit/Kit.cpp:594
wsd-00001-00118 2025-04-02 06:09:00.016331 +0000 [ docbroker_005 ] ERR  #17: Socket write returned -1 (EPIPE: Broken pipe)| net/Socket.hpp:1622
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
```

Nextcloud documentation mentiones to enable Previews[](https://docs.nextcloud.com/server/latest/admin_manual/office/configuration.html#previews)
In order to allow Nextcloud to use the coolwsd conversion API to generate previews, the Nextcloud host IP needs to be added to the allow list: `sudo coolconfig set net.post_allow.host 10.0.0.4`
that's why I have added ` extra_params: --o:net.post_allow.host=10.0.20.100` to the Helm values but this also does not solve the trouble.

Currently I am pretty clueless what else I can debug.

Any suggestiongs?
